#!/bin/bash
set -e

TARGET='Fire'
EXE="/Library/Input Methods/${TARGET}.app/Contents/MacOS/${TARGET}"

login_user=$(/usr/bin/stat -f%Su /dev/console)

pkill -9 -f "Fire.app/Contents/MacOS/Fire" 2>/dev/null || true

"${EXE}" --register-input-source
/usr/bin/sudo -u "${login_user}" "${EXE}" --enable || true
/usr/bin/sudo -u "${login_user}" "${EXE}" --select || true
