#!/bin/bash
set -e

TARGET='Fire'
EXE="/Library/Input Methods/${TARGET}.app/Contents/MacOS/${TARGET}"

login_user=$(/usr/bin/stat -f%Su /dev/console)

/usr/bin/sudo -u "${login_user}" /usr/bin/pkill -9 "${TARGET}" || true

"${EXE}" --register-input-source
/usr/bin/sudo -u "${login_user}" "${EXE}" --enable-input-source
/usr/bin/sudo -u "${login_user}" "${EXE}" --select-input-source
