#!/bin/bash

TARGET='Fire'

login_user=`/usr/bin/stat -f%Su /dev/console`

/usr/bin/sudo -u "${login_user}" pkill -9 "${TARGET}"
/usr/bin/sudo -u "${login_user}" rm -rf "/Library/Input Methods/${TARGET}.app"

echo "${Target} input method registered and activated successfully"
