#!/bin/bash

PROJECT_ROOT="$(cd "$(dirname "$BASH_SOURCE")/.."; pwd)"
TARGET="Fire"
WORKSPACE="$PROJECT_ROOT/${TARGET}.xcworkspace"
APP_NAME="业火输入法"

EXPORT_PATH="$PROJECT_ROOT/dist"
EXPORT_ARCHIVE="$EXPORT_PATH/archive.xcarchive"
EXPORT_APP="$EXPORT_PATH/$TARGET.app"
EXPORT_ZIP="$EXPORT_PATH/$TARGET.zip"
EXPORT_INSTALLER="$EXPORT_PATH/FireInstaller.pkg"
EXPORT_INSTALLER_ZIP="$EXPORT_PATH/FireInstaller.zip"

echo "PROJECT_ROOT=$PROJECT_ROOT"