name: release

on:
  release:
    types: ['published']

jobs:
  release:
    runs-on: macOS-latest
    
    steps:
    - uses: actions/checkout@v1

    - name: update version
      run: |
        PRODUCT_SETTINGS_PATH=./Fire/Info.plist
        version=$(git describe --tags `git rev-list --tags --max-count=1`)
        /usr/libexec/PlistBuddy -c "Set :CFBundleShortVersionString $version" $PRODUCT_SETTINGS_PATH

    - name: install depencies
      run: pod install
    - name: build
      run: ./build_app.sh
    - name: make FireInstaller.pkg
      env:
        sparkle_key: ${{ secrets.sparkle_key }}
      run: ./package/make_package.sh

    - name: sign update
      run: echo "sign update"

    - name: release
      uses: AButler/upload-release-assets@v1.0
      with:
        files: 'apps/Fire.zip,apps/FireInstaller.pkg'
        repo-token: ${{ secrets.GITHUB_TOKEN }}

    - name: install & config coscmd
      env:
        oss_appid: ${{ secrets.oss_appid }}
        oss_secret: ${{ secrets.oss_secret }}
      run: |
        pip install pip==9.0.0 && pip install coscmd
        coscmd config -a $oss_appid -s $oss_secret -b person-1253524658 -r ap-beijing
    - name: upload app and appcast
      run: |
        coscmd upload ./apps/Fire.zip cloudfn/apps/fire/Fire.zip
        coscmd upload ./apps/appcast.xml cloudfn/apps/fire/appcast.xml
